#
# Makefile for MMI_INF Motherboard drivers
#

# Set mmi_info module
obj-$(CONFIG_MMI_INFO) += mmi_info.o

# Include objects for build kernel
mmi_info-objs += mmi_storage_info.o
mmi_info-objs += mmi_ram_info.o
mmi_info-objs += mmi_unit_info.o
mmi_info-objs += mmi_boot_info.o
mmi_info-objs += mmi_info_main.o